project_name: adl-lsp
release:
  github:
    owner: wxio
    name: tron-go
  draft: true
  # disable: true

builds:
  - binary: adl-lsp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: amd64
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      post: vsce package

archives:
  - id: vsix
    format: binary
    files:
      -  tron-*.vsix

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"
